In [1]:
from sklearn.datasets import load_iris

x_data = load_iris().data
y_data =  load_iris().target

In [2]:
import pandas as pd 

x_data = pd.DataFrame(x_data,columns=['花萼长度','花萼宽度','花瓣长度','花瓣宽度'])
pd.set_option('display.unicode.east_asian_width',True)
x_data

花萼长度  花萼宽度  花瓣长度  花瓣宽度
0         5.1       3.5       1.4       0.2
1         4.9       3.0       1.4       0.2
2         4.7       3.2       1.3       0.2
3         4.6       3.1       1.5       0.2
4         5.0       3.6       1.4       0.2
..        ...       ...       ...       ...
145       6.7       3.0       5.2       2.3
146       6.3       2.5       5.0       1.9
147       6.5       3.0       5.2       2.0
148       6.2       3.4       5.4       2.3
149       5.9       3.0       5.1       1.8

[150 rows x 4 columns]

In [4]:
x_train = x_data[:-30]
y_train = y_data[:-30]
x_test = x_data[-30:]
y_test = y_data[-30:]


In [9]:
import tensorflow as tf

train_db = tf.data.Dataset.from_tensor_slices((x_train,y_train)).batch(32)
test_db = tf.data.Dataset.from_tensor_slices((x_test,y_test)).batch(32)



In [10]:
next(iter(train_db))

(<tf.Tensor: shape=(32, 4), dtype=float64, numpy=
 array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1

In [18]:
model = tf.keras.models.Sequential([tf.keras.layers.Dense(128,activation='relu')
                                    ,tf.keras.layers.Dense(4,activation='softmax')])
model.compile(optimizer=tf.keras.optimizers.SGD(lr=0.1),
              loss ='sparse_categorical_crossentropy',metrics=['accuracy'])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

model.fit(train_db,epochs=500,validation_data=test_db)


/Users/hewenpang/miniforge3/envs/tf/lib/python3.9/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:374: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(


Epoch 1/500


2024-01-03 22:14:49.624679: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


4/4 [==============================] - 1s 65ms/step - loss: 2.8841 - accuracy: 0.4500 - val_loss: 0.0157 - val_accuracy: 1.0000
Epoch 2/500
4/4 [==============================] - 0s 10ms/step - loss: 1.8445 - accuracy: 0.1833 - val_loss: 1.0248 - val_accuracy: 1.0000
Epoch 3/500
4/4 [==============================] - 0s 10ms/step - loss: 1.1494 - accuracy: 0.4500 - val_loss: 0.8381 - val_accuracy: 1.0000
Epoch 4/500
4/4 [==============================] - 0s 8ms/step - loss: 1.0421 - accuracy: 0.4500 - val_loss: 0.6049 - val_accuracy: 1.0000
Epoch 5/500
1/4 [======>.......................] - ETA: 0s - loss: 0.9069 - accuracy: 1.0000

2024-01-03 22:14:50.541978: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


4/4 [==============================] - 0s 11ms/step - loss: 0.9485 - accuracy: 0.5083 - val_loss: 0.4390 - val_accuracy: 1.0000
Epoch 6/500
4/4 [==============================] - 0s 9ms/step - loss: 0.8841 - accuracy: 0.6000 - val_loss: 0.3370 - val_accuracy: 1.0000
Epoch 7/500
4/4 [==============================] - 0s 9ms/step - loss: 0.7764 - accuracy: 0.6833 - val_loss: 0.2484 - val_accuracy: 1.0000
Epoch 8/500
4/4 [==============================] - 0s 10ms/step - loss: 0.7448 - accuracy: 0.6583 - val_loss: 0.2276 - val_accuracy: 1.0000
Epoch 9/500
4/4 [==============================] - 0s 14ms/step - loss: 0.6571 - accuracy: 0.6833 - val_loss: 0.1915 - val_accuracy: 1.0000
Epoch 10/500
4/4 [==============================] - 0s 8ms/step - loss: 0.6594 - accuracy: 0.6667 - val_loss: 0.2403 - val_accuracy: 1.0000
Epoch 11/500
4/4 [==============================] - 0s 8ms/step - loss: 0.5777 - accuracy: 0.7083 - val_loss: 0.1541 - val_accuracy: 1.0000
Epoch 12/500
4/4 [================

In [9]:
import tensorflow as tf
tensor1 = tf.constant([[1, 2],[5, 6]])
tensor2 = tf.constant([[3, 4]])

concat_res = tf.concat([tensor1,tensor2],axis=0)
concat_res

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 6],
       [3, 4]])>

In [14]:
tensor3 = tf.constant([1, 2])
tensor4 = tf.constant([3, 4])
stack_res = tf.stack([tensor3,tensor4],axis=0)
stack_res

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>