In [1]:
from sklearn.datasets import load_iris

x_data = load_iris().data
y_data =  load_iris().target

In [2]:
import pandas as pd 

x_data = pd.DataFrame(x_data,columns=['花萼长度','花萼宽度','花瓣长度','花瓣宽度'])
pd.set_option('display.unicode.east_asian_width',True)
x_data

花萼长度  花萼宽度  花瓣长度  花瓣宽度
0         5.1       3.5       1.4       0.2
1         4.9       3.0       1.4       0.2
2         4.7       3.2       1.3       0.2
3         4.6       3.1       1.5       0.2
4         5.0       3.6       1.4       0.2
..        ...       ...       ...       ...
145       6.7       3.0       5.2       2.3
146       6.3       2.5       5.0       1.9
147       6.5       3.0       5.2       2.0
148       6.2       3.4       5.4       2.3
149       5.9       3.0       5.1       1.8

[150 rows x 4 columns]

In [4]:
x_train = x_data[:-30]
y_train = y_data[:-30]
x_test = x_data[-30:]
y_test = y_data[-30:]


In [5]:
import tensorflow as tf

train_db = tf.data.Dataset.from_tensor_slices((x_train,y_train)).batch(32)
test_db = tf.data.Dataset.from_tensor_slices((x_test,y_test)).batch(32)

model = tf.keras.models.Sequential([tf.keras.layers.Dense(4)])
model.compile(optimizer=tf.keras.optimizers.SGD(lr=0.1),
              loss ='mse'
              )                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

model.fit(x_train,y_train,batch_size =32,epochs = 500,validation_split = 0.2,validation_freq =20)

model.summary()


Epoch 1/500



3/3 [==============================] - 0s 3ms/step - loss: 11.2590
Epoch 2/500
3/3 [==============================] - 0s 2ms/step - loss: 2.1902
Epoch 3/500
3/3 [==============================] - 0s 1ms/step - loss: 0.5601
Epoch 4/500
3/3 [==============================] - 0s 2ms/step - loss: 0.2640
Epoch 5/500
3/3 [==============================] - 0s 2ms/step - loss: 0.2042
Epoch 6/500
3/3 [==============================] - 0s 1ms/step - loss: 0.1865
Epoch 7/500
3/3 [==============================] - 0s 2ms/step - loss: 0.1761
Epoch 8/500
3/3 [==============================] - 0s 1ms/step - loss: 0.1681
Epoch 9/500
3/3 [==============================] - 0s 1ms/step - loss: 0.1601
Epoch 10/500
3/3 [==============================] - 0s 2ms/step - loss: 0.1554
Epoch 11/500
3/3 [==============================] - 0s 1ms/step - loss: 0.1466
Epoch 12/500
3/3 [==============================] - 0s 1ms/step - loss: 0.1409
Epoch 13/500
3/3 [==============================] - 0s 1ms/step - loss: 

In [9]:
import tensorflow as tf
tensor1 = tf.constant([[1, 2],[5, 6]])
tensor2 = tf.constant([[3, 4]])

concat_res = tf.concat([tensor1,tensor2],axis=0)
concat_res

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 6],
       [3, 4]])>

In [14]:
tensor3 = tf.constant([1, 2])
tensor4 = tf.constant([3, 4])
stack_res = tf.stack([tensor3,tensor4],axis=0)
stack_res

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>